//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterimSearch.User_Controls.Sent_Offer.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class SentOffer_Val : global::System.Configuration.ApplicationSettingsBase {
        
        private static SentOffer_Val defaultInstance = ((SentOffer_Val)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SentOffer_Val())));
        
        public static SentOffer_Val Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Propositions de missions envoyées")]
        public string SentOfferTitle {
            get {
                return ((string)(this["SentOfferTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aucune proposition de mission n\'a été envoyée.")]
        public string lbl_anyItem_Content {
            get {
                return ((string)(this["lbl_anyItem_Content"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" - ")]
        public string BetweenTime {
            get {
                return ((string)(this["BetweenTime"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Date d\'envoi de la proposition de mission :")]
        public string lbl_temporarySendDate {
            get {
                return ((string)(this["lbl_temporarySendDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mission acceptée par l\'intérimaire")]
        public string AcceptedMission {
            get {
                return ((string)(this["AcceptedMission"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mission refusée par l\'intérimaire")]
        public string RejectedMission {
            get {
                return ((string)(this["RejectedMission"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mission acceptée...")]
        public string AcceptMission {
            get {
                return ((string)(this["AcceptMission"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mission refusée...")]
        public string RejectMission {
            get {
                return ((string)(this["RejectMission"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Etes-vous sûr de vouloir confirmer l\'acceptation de la mission par\r\n")]
        public string ConfirmAcceptMission {
            get {
                return ((string)(this["ConfirmAcceptMission"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Confirmation d\'acceptation de la mission")]
        public string ConfirmAcceptMissionTitle {
            get {
                return ((string)(this["ConfirmAcceptMissionTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" ?")]
        public string Ask {
            get {
                return ((string)(this["Ask"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L\'enregistrement de l\'acceptation et des annulations de la mission ont échoué.")]
        public string NullSetAvaibilityAcceptedOrAbortedMission {
            get {
                return ((string)(this["NullSetAvaibilityAcceptedOrAbortedMission"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L\'adresse email de l\'intérimaire est incorrecte.")]
        public string NullEmailAdress {
            get {
                return ((string)(this["NullEmailAdress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Impossible de charger les informations de l\'intérimaire.")]
        public string NullInformations {
            get {
                return ((string)(this["NullInformations"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Impossible de trouver l\'intérimaire.")]
        public string NullTemporaryID {
            get {
                return ((string)(this["NullTemporaryID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Le contenu de l\'email est inexistant.")]
        public string NullMessage {
            get {
                return ((string)(this["NullMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Envoi de l\'email confirmé.")]
        public string EmailSent {
            get {
                return ((string)(this["EmailSent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Informations")]
        public string InformationTitle {
            get {
                return ((string)(this["InformationTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L\'envoi de l\'email a échoué.")]
        public string NullSendEmail {
            get {
                return ((string)(this["NullSendEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("x@x.x")]
        public string FakeEmailAdress {
            get {
                return ((string)(this["FakeEmailAdress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Impossible de charger les informations de la mission.")]
        public string NullAvaibilityInformations {
            get {
                return ((string)(this["NullAvaibilityInformations"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Impossible de charger l\'adresse email ou la date de mission.")]
        public string NullEmailAdressOrDate {
            get {
                return ((string)(this["NullEmailAdressOrDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Etes-vous sûr de vouloir confirmer le refus de la mission par\r\n")]
        public string ConfirmRejectMission {
            get {
                return ((string)(this["ConfirmRejectMission"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Confirmation de refus de mission envoyée")]
        public string ConfirmRejectMissionTitle {
            get {
                return ((string)(this["ConfirmRejectMissionTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Autres actions...")]
        public string OtherActionMission {
            get {
                return ((string)(this["OtherActionMission"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mission annulée...")]
        public string AbortMission {
            get {
                return ((string)(this["AbortMission"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Confirmation d\'annulation de mission envoyée")]
        public string ConfirmAbortMissionTitle {
            get {
                return ((string)(this["ConfirmAbortMissionTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Etes-vous sûr de vouloir confirmer l\'annulation de la mission par\r\n")]
        public string ConfirmAbortMission {
            get {
                return ((string)(this["ConfirmAbortMission"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Impossible d\'envoyer des emails sans le client de messagerie électronique Microso" +
            "ft Outlook.")]
        public string NullOutlookApplication {
            get {
                return ((string)(this["NullOutlookApplication"]));
            }
        }
    }
}
