SET IDENTITY_INSERT [dbo].[tbl_city] ON
INSERT INTO [dbo].[tbl_city] ([idCity], [city_Name], [idRegion]) VALUES (1, N'Lausanne', 1)
INSERT INTO [dbo].[tbl_city] ([idCity], [city_Name], [idRegion]) VALUES (2, N'Genève', 4)
INSERT INTO [dbo].[tbl_city] ([idCity], [city_Name], [idRegion]) VALUES (3, N'Zurich', 8)
INSERT INTO [dbo].[tbl_city] ([idCity], [city_Name], [idRegion]) VALUES (4, N'Aubonne', 1)
INSERT INTO [dbo].[tbl_city] ([idCity], [city_Name], [idRegion]) VALUES (5, N'Vallorbe', 1)
INSERT INTO [dbo].[tbl_city] ([idCity], [city_Name], [idRegion]) VALUES (6, N'Sainte-Croix', 1)
INSERT INTO [dbo].[tbl_city] ([idCity], [city_Name], [idRegion]) VALUES (7, N'Yverdon-Les-Bains', 1)
INSERT INTO [dbo].[tbl_city] ([idCity], [city_Name], [idRegion]) VALUES (8, N'Vuiteboeuf', 1)
INSERT INTO [dbo].[tbl_city] ([idCity], [city_Name], [idRegion]) VALUES (9, N'Villeneuve', 1)
INSERT INTO [dbo].[tbl_city] ([idCity], [city_Name], [idRegion]) VALUES (10, N'Villars-Sainte-Croix', 1)
INSERT INTO [dbo].[tbl_city] ([idCity], [city_Name], [idRegion]) VALUES (11, N'Vevey', 1)
INSERT INTO [dbo].[tbl_city] ([idCity], [city_Name], [idRegion]) VALUES (12, N'Sullens', 1)
INSERT INTO [dbo].[tbl_city] ([idCity], [city_Name], [idRegion]) VALUES (13, N'Pully', 1)
INSERT INTO [dbo].[tbl_city] ([idCity], [city_Name], [idRegion]) VALUES (14, N'Renens', 1)
INSERT INTO [dbo].[tbl_city] ([idCity], [city_Name], [idRegion]) VALUES (15, N'Berne', 5)
INSERT INTO [dbo].[tbl_city] ([idCity], [city_Name], [idRegion]) VALUES (16, N'Pontarlier', 18)
INSERT INTO [dbo].[tbl_city] ([idCity], [city_Name], [idRegion]) VALUES (17, N'Besançon', 18)
INSERT INTO [dbo].[tbl_city] ([idCity], [city_Name], [idRegion]) VALUES (18, N'Dijon', 18)
SET IDENTITY_INSERT [dbo].[tbl_city] OFF
