SET IDENTITY_INSERT [dbo].[tbl_employmentAgency] ON
INSERT INTO [dbo].[tbl_employmentAgency] ([idEmploymentAgency], [employmentAgency_Name], [employmentAgency_Street], [employmentAgency_Number], [employmentAgency_PostCode], [idCity], [employmentAgency_EmailAdress], [employmentAgency_PhoneNumber]) VALUES (1, N'Swiss Interim', N'Rue Philippe-François-de-Langa', 9, N'1003', 1, N'lausanne@swissinterim.ch', 41213425000)
INSERT INTO [dbo].[tbl_employmentAgency] ([idEmploymentAgency], [employmentAgency_Name], [employmentAgency_Street], [employmentAgency_Number], [employmentAgency_PostCode], [idCity], [employmentAgency_EmailAdress], [employmentAgency_PhoneNumber]) VALUES (2, N'ManPower', N'Rue Mauborget', 1, N'1003', 1, N'media@manpower.ch', 41583072323)
INSERT INTO [dbo].[tbl_employmentAgency] ([idEmploymentAgency], [employmentAgency_Name], [employmentAgency_Street], [employmentAgency_Number], [employmentAgency_PostCode], [idCity], [employmentAgency_EmailAdress], [employmentAgency_PhoneNumber]) VALUES (3, N'Unique', N'Rue du Petit-Chêne', 11, N'1003', 1, N'info@uniquerh.ch', 41213104090)
INSERT INTO [dbo].[tbl_employmentAgency] ([idEmploymentAgency], [employmentAgency_Name], [employmentAgency_Street], [employmentAgency_Number], [employmentAgency_PostCode], [idCity], [employmentAgency_EmailAdress], [employmentAgency_PhoneNumber]) VALUES (4, N'Adecco', N'Rue du Petit-Chêne', 38, N'1002', 1, N'lausanne.industrial@adecco.ch', 41213434000)
INSERT INTO [dbo].[tbl_employmentAgency] ([idEmploymentAgency], [employmentAgency_Name], [employmentAgency_Street], [employmentAgency_Number], [employmentAgency_PostCode], [idCity], [employmentAgency_EmailAdress], [employmentAgency_PhoneNumber]) VALUES (5, N'Crit Intérim', N'Rue du Mont-Blanc', 11, N'1201', 2, N'lausanne@crit.ch', 41229082929)
INSERT INTO [dbo].[tbl_employmentAgency] ([idEmploymentAgency], [employmentAgency_Name], [employmentAgency_Street], [employmentAgency_Number], [employmentAgency_PostCode], [idCity], [employmentAgency_EmailAdress], [employmentAgency_PhoneNumber]) VALUES (6, N'Samsic Emploi', N'Rue Haldimand', 2, N'1003', 1, N'info-lausanne@samsic-emploi.ch', 41213414160)
INSERT INTO [dbo].[tbl_employmentAgency] ([idEmploymentAgency], [employmentAgency_Name], [employmentAgency_Street], [employmentAgency_Number], [employmentAgency_PostCode], [idCity], [employmentAgency_EmailAdress], [employmentAgency_PhoneNumber]) VALUES (7, N'Max Studer', N'Rue des Terreaux', 29, N'1003', 1, N'lausanne@maxstuder.ch', 41219663000)
INSERT INTO [dbo].[tbl_employmentAgency] ([idEmploymentAgency], [employmentAgency_Name], [employmentAgency_Street], [employmentAgency_Number], [employmentAgency_PostCode], [idCity], [employmentAgency_EmailAdress], [employmentAgency_PhoneNumber]) VALUES (8, N'A à Z Emploi', N'Rue de l''Ale', 25, N'1003', 1, N'vd@aazemplois.ch', 41217030808)
INSERT INTO [dbo].[tbl_employmentAgency] ([idEmploymentAgency], [employmentAgency_Name], [employmentAgency_Street], [employmentAgency_Number], [employmentAgency_PostCode], [idCity], [employmentAgency_EmailAdress], [employmentAgency_PhoneNumber]) VALUES (9, N'Planet Intérim', N'Avenue Louis-Ruchonnet', 1, N'1003', 1, N'info@planetinterim.ch', 41213434444)
INSERT INTO [dbo].[tbl_employmentAgency] ([idEmploymentAgency], [employmentAgency_Name], [employmentAgency_Street], [employmentAgency_Number], [employmentAgency_PostCode], [idCity], [employmentAgency_EmailAdress], [employmentAgency_PhoneNumber]) VALUES (10, N'Cible Emploi', N'Rue de Genève', 17, N'1003', 1, N'info@cibleemploi.ch', 41213400040)
SET IDENTITY_INSERT [dbo].[tbl_employmentAgency] OFF
