SET IDENTITY_INSERT [dbo].[tbl_region] ON
INSERT INTO [dbo].[tbl_region] ([idRegion], [region_Name], [idCountry]) VALUES (1, N'Vaud', 2)
INSERT INTO [dbo].[tbl_region] ([idRegion], [region_Name], [idCountry]) VALUES (2, N'Valais', 2)
INSERT INTO [dbo].[tbl_region] ([idRegion], [region_Name], [idCountry]) VALUES (3, N'Jura', 2)
INSERT INTO [dbo].[tbl_region] ([idRegion], [region_Name], [idCountry]) VALUES (4, N'Genève', 2)
INSERT INTO [dbo].[tbl_region] ([idRegion], [region_Name], [idCountry]) VALUES (5, N'Berne', 2)
INSERT INTO [dbo].[tbl_region] ([idRegion], [region_Name], [idCountry]) VALUES (6, N'Fribourg', 2)
INSERT INTO [dbo].[tbl_region] ([idRegion], [region_Name], [idCountry]) VALUES (7, N'Neuchâtel', 2)
INSERT INTO [dbo].[tbl_region] ([idRegion], [region_Name], [idCountry]) VALUES (8, N'Zurich', 2)
INSERT INTO [dbo].[tbl_region] ([idRegion], [region_Name], [idCountry]) VALUES (9, N'Tessin', 2)
INSERT INTO [dbo].[tbl_region] ([idRegion], [region_Name], [idCountry]) VALUES (10, N'Lucerne', 2)
INSERT INTO [dbo].[tbl_region] ([idRegion], [region_Name], [idCountry]) VALUES (11, N'Grisons', 2)
INSERT INTO [dbo].[tbl_region] ([idRegion], [region_Name], [idCountry]) VALUES (12, N'Uri', 2)
INSERT INTO [dbo].[tbl_region] ([idRegion], [region_Name], [idCountry]) VALUES (13, N'Zoug', 2)
INSERT INTO [dbo].[tbl_region] ([idRegion], [region_Name], [idCountry]) VALUES (14, N'Obwald', 2)
INSERT INTO [dbo].[tbl_region] ([idRegion], [region_Name], [idCountry]) VALUES (15, N'Schwytz', 2)
INSERT INTO [dbo].[tbl_region] ([idRegion], [region_Name], [idCountry]) VALUES (16, N'Soleure', 2)
INSERT INTO [dbo].[tbl_region] ([idRegion], [region_Name], [idCountry]) VALUES (17, N'Argovie', 2)
INSERT INTO [dbo].[tbl_region] ([idRegion], [region_Name], [idCountry]) VALUES (18, N'Franche-Comté', 1)
INSERT INTO [dbo].[tbl_region] ([idRegion], [region_Name], [idCountry]) VALUES (19, N'Alsace', 1)
INSERT INTO [dbo].[tbl_region] ([idRegion], [region_Name], [idCountry]) VALUES (20, N'Rhône-Alpes', 1)
INSERT INTO [dbo].[tbl_region] ([idRegion], [region_Name], [idCountry]) VALUES (21, N'Lorraine', 1)
SET IDENTITY_INSERT [dbo].[tbl_region] OFF
