//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterimSearch.User_Controls.Profile.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Profile_Code : global::System.Configuration.ApplicationSettingsBase {
        
        private static Profile_Code defaultInstance = ((Profile_Code)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Profile_Code())));
        
        public static Profile_Code Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^\\w+@[a-zA-Z_]+?\\.[a-zA-Z]{2,3}")]
        public string regexEmailAdress {
            get {
                return ((string)(this["regexEmailAdress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mailto:")]
        public string Mailto {
            get {
                return ((string)(this["Mailto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Interim Search\\Temporary Work Reports\\")]
        public string TemporaryWorkReports {
            get {
                return ((string)(this["TemporaryWorkReports"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_")]
        public string Underscore {
            get {
                return ((string)(this["Underscore"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".pdf")]
        public string DotPDF {
            get {
                return ((string)(this["DotPDF"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\")]
        public string Slash {
            get {
                return ((string)(this["Slash"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Templates\\Work Reports\\template_WorkReport.html")]
        public string TemplateWorkReport {
            get {
                return ((string)(this["TemplateWorkReport"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@EmployementAgency_Name")]
        public string EmployementAgency_Name {
            get {
                return ((string)(this["EmployementAgency_Name"]));
            }
            set {
                this["EmployementAgency_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@EmployementAgency_Number")]
        public string EmployementAgency_Number {
            get {
                return ((string)(this["EmployementAgency_Number"]));
            }
            set {
                this["EmployementAgency_Number"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@EmployementAgency_Street")]
        public string EmployementAgency_Street {
            get {
                return ((string)(this["EmployementAgency_Street"]));
            }
            set {
                this["EmployementAgency_Street"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@EmployementAgency_PostCode")]
        public string EmployementAgency_PostCode {
            get {
                return ((string)(this["EmployementAgency_PostCode"]));
            }
            set {
                this["EmployementAgency_PostCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@EmployementAgency_City")]
        public string EmployementAgency_City {
            get {
                return ((string)(this["EmployementAgency_City"]));
            }
            set {
                this["EmployementAgency_City"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@EmployementAgency_Region")]
        public string EmployementAgency_Region {
            get {
                return ((string)(this["EmployementAgency_Region"]));
            }
            set {
                this["EmployementAgency_Region"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@EmployementAgency_Contry")]
        public string EmployementAgency_Contry {
            get {
                return ((string)(this["EmployementAgency_Contry"]));
            }
            set {
                this["EmployementAgency_Contry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@EmployementAgency_PhoneNumber")]
        public string EmployementAgency_PhoneNumber {
            get {
                return ((string)(this["EmployementAgency_PhoneNumber"]));
            }
            set {
                this["EmployementAgency_PhoneNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@EmployementAgency_EmailAdress")]
        public string EmployementAgency_EmailAdress {
            get {
                return ((string)(this["EmployementAgency_EmailAdress"]));
            }
            set {
                this["EmployementAgency_EmailAdress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@Temporary_Title")]
        public string Temporary_Title {
            get {
                return ((string)(this["Temporary_Title"]));
            }
            set {
                this["Temporary_Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@Temporary_Name")]
        public string Temporary_Name {
            get {
                return ((string)(this["Temporary_Name"]));
            }
            set {
                this["Temporary_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@Temporary_FirstName")]
        public string Temporary_FirstName {
            get {
                return ((string)(this["Temporary_FirstName"]));
            }
            set {
                this["Temporary_FirstName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@Temporary_BirthDate")]
        public string Temporary_BirthDate {
            get {
                return ((string)(this["Temporary_BirthDate"]));
            }
            set {
                this["Temporary_BirthDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@Temporary_Profession")]
        public string Temporary_Profession {
            get {
                return ((string)(this["Temporary_Profession"]));
            }
            set {
                this["Temporary_Profession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@Generate_Date")]
        public string Generate_Date {
            get {
                return ((string)(this["Generate_Date"]));
            }
            set {
                this["Generate_Date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@Avaibility_Data")]
        public string Avaibility_Data {
            get {
                return ((string)(this["Avaibility_Data"]));
            }
            set {
                this["Avaibility_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@WorkTimetable_FinaleSum")]
        public string WorkTimetable_FinaleSum {
            get {
                return ((string)(this["WorkTimetable_FinaleSum"]));
            }
            set {
                this["WorkTimetable_FinaleSum"] = value;
            }
        }
    }
}
