//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterimSearch.User_Controls.Profile.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Profile_Err : global::System.Configuration.ApplicationSettingsBase {
        
        private static Profile_Err defaultInstance = ((Profile_Err)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Profile_Err())));
        
        public static Profile_Err Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Erreur au sein du programme")]
        public string ErrorTitle {
            get {
                return ((string)(this["ErrorTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"Profile.CreateWorkReport\"" +
            ".")]
        public string CreateWorkReport {
            get {
                return ((string)(this["CreateWorkReport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"Profile.TryOpenFile\".")]
        public string TryOpenFile {
            get {
                return ((string)(this["TryOpenFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"Profile.SaveWorkReport\".")]
        public string SaveWorkReport {
            get {
                return ((string)(this["SaveWorkReport"]));
            }
        }
    }
}
