//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterimSearch.User_Controls.Profile.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Profile_Val : global::System.Configuration.ApplicationSettingsBase {
        
        private static Profile_Val defaultInstance = ((Profile_Val)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Profile_Val())));
        
        public static Profile_Val Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Profil d\'intérimaire")]
        public string ProfileTitle {
            get {
                return ((string)(this["ProfileTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" ans")]
        public string Year {
            get {
                return ((string)(this["Year"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+ ")]
        public string InternationalSymbol {
            get {
                return ((string)(this["InternationalSymbol"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Impossible de charger les informations de l\'intérimaire.")]
        public string TemporaryInformations {
            get {
                return ((string)(this["TemporaryInformations"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Impossible de créer ou de sauvegarder le rapport de travail.")]
        public string NullWorkReport {
            get {
                return ((string)(this["NullWorkReport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("x@x.x")]
        public string FakeEmailAdress {
            get {
                return ((string)(this["FakeEmailAdress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Impossible de charger les informations de l\'agence d\'intérim.")]
        public string NullEmploymentAgencyID {
            get {
                return ((string)(this["NullEmploymentAgencyID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cet intérimaire n\'a effectué aucune mission pour l\'instant.")]
        public string NullWorkReportInformations {
            get {
                return ((string)(this["NullWorkReportInformations"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Informations")]
        public string InformationTitle {
            get {
                return ((string)(this["InformationTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Impossible d\'ouvrir un email vierge sans un client de messagerie électronique.")]
        public string NullEmailApplication {
            get {
                return ((string)(this["NullEmailApplication"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L\'adresse email de l\'intérimaire est incorrecte.")]
        public string NullEmailAdress {
            get {
                return ((string)(this["NullEmailAdress"]));
            }
        }
    }
}
