//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterimSearch.User_Controls.Graphs_And_Stats.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class GraphStat_Err : global::System.Configuration.ApplicationSettingsBase {
        
        private static GraphStat_Err defaultInstance = ((GraphStat_Err)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GraphStat_Err())));
        
        public static GraphStat_Err Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Erreur au sein du programme")]
        public string ErrorTitle {
            get {
                return ((string)(this["ErrorTitle"]));
            }
        }
    }
}
