//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterimSearch.Interim_Database.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Interim_Err : global::System.Configuration.ApplicationSettingsBase {
        
        private static Interim_Err defaultInstance = ((Interim_Err)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Interim_Err())));
        
        public static Interim_Err Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Erreur au sein du programme")]
        public string ErrorTitle {
            get {
                return ((string)(this["ErrorTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetProfes" +
            "sion\".")]
        public string GetProfession {
            get {
                return ((string)(this["GetProfession"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetWorkTi" +
            "metable\".")]
        public string GetWorkTimetable {
            get {
                return ((string)(this["GetWorkTimetable"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetTempor" +
            "aryFirstName\".")]
        public string GetTemporaryFirstName {
            get {
                return ((string)(this["GetTemporaryFirstName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetTempor" +
            "aryID\".")]
        public string GetTemporaryID {
            get {
                return ((string)(this["GetTemporaryID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetTempor" +
            "aryName\".")]
        public string GetTemporaryName {
            get {
                return ((string)(this["GetTemporaryName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetTempor" +
            "aryNbrYearExp\".")]
        public string GetTemporaryNbrYearExp {
            get {
                return ((string)(this["GetTemporaryNbrYearExp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetTempor" +
            "aryAge\".")]
        public string GetTemporaryAge {
            get {
                return ((string)(this["GetTemporaryAge"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetTempor" +
            "aryCity\".")]
        public string GetTemporaryCity {
            get {
                return ((string)(this["GetTemporaryCity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetTempor" +
            "aryTitle\".")]
        public string GetTemporaryTitle {
            get {
                return ((string)(this["GetTemporaryTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetServic" +
            "e\".")]
        public string GetService {
            get {
                return ((string)(this["GetService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetTempor" +
            "aryEmailAdress\".")]
        public string GetTemporaryEmailAdress {
            get {
                return ((string)(this["GetTemporaryEmailAdress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.SetSendDa" +
            "teAndService\".")]
        public string SetSendDateAndService {
            get {
                return ((string)(this["SetSendDateAndService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetAvaibi" +
            "lityID\".")]
        public string GetAvaibilityID {
            get {
                return ((string)(this["GetAvaibilityID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetTempor" +
            "aryStreet\".")]
        public string GetTemporaryStreet {
            get {
                return ((string)(this["GetTemporaryStreet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetTempor" +
            "aryNumber\".")]
        public string GetTemporaryNumber {
            get {
                return ((string)(this["GetTemporaryNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetTempor" +
            "aryPostCode\".")]
        public string GetTemporaryPostCode {
            get {
                return ((string)(this["GetTemporaryPostCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetTempor" +
            "aryRegion\".")]
        public string GetTemporaryRegion {
            get {
                return ((string)(this["GetTemporaryRegion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetTempor" +
            "aryPhoneNumber\".")]
        public string GetTemporaryPhoneNumber {
            get {
                return ((string)(this["GetTemporaryPhoneNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetTempor" +
            "aryProfession\".")]
        public string GetTemporaryProfession {
            get {
                return ((string)(this["GetTemporaryProfession"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetTempor" +
            "aryEmploymentAgency\".")]
        public string GetTemporaryEmploymentAgency {
            get {
                return ((string)(this["GetTemporaryEmploymentAgency"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetTempor" +
            "aryCertified\".")]
        public string GetTemporaryCertified {
            get {
                return ((string)(this["GetTemporaryCertified"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetAvaibi" +
            "lityDate\".")]
        public string GetAvaibilityDate {
            get {
                return ((string)(this["GetAvaibilityDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetAvaibi" +
            "lityIDAll\".")]
        public string GetAvaibilityIDAll {
            get {
                return ((string)(this["GetAvaibilityIDAll"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetAvaibi" +
            "lityTemporaryID\".")]
        public string GetAvaibilityTemporaryID {
            get {
                return ((string)(this["GetAvaibilityTemporaryID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetTempor" +
            "aryService\".")]
        public string GetTemporaryService {
            get {
                return ((string)(this["GetTemporaryService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetTempor" +
            "arySendDate\".")]
        public string GetTemporarySendDate {
            get {
                return ((string)(this["GetTemporarySendDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetTempor" +
            "aryAcceptedMission\".")]
        public string GetTemporaryAcceptedMission {
            get {
                return ((string)(this["GetTemporaryAcceptedMission"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.SetStateM" +
            "ission\".")]
        public string SetStateMission {
            get {
                return ((string)(this["SetStateMission"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetTempor" +
            "aryDate\".")]
        public string GetTemporaryDate {
            get {
                return ((string)(this["GetTemporaryDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetTempor" +
            "aryWorkTimetableStart\".")]
        public string GetTemporaryWorkTimetableStart {
            get {
                return ((string)(this["GetTemporaryWorkTimetableStart"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetTempor" +
            "aryWorkTimetableEnd\".")]
        public string GetTemporaryWorkTimetableEnd {
            get {
                return ((string)(this["GetTemporaryWorkTimetableEnd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.SetAbortM" +
            "ission\".")]
        public string SetAbortMission {
            get {
                return ((string)(this["SetAbortMission"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetAbortA" +
            "vibilityID\".")]
        public string GetAbortAvibilityID {
            get {
                return ((string)(this["GetAbortAvibilityID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetAvaibi" +
            "lityWorkTimetable\".")]
        public string GetAvaibilityWorkTimetable {
            get {
                return ((string)(this["GetAvaibilityWorkTimetable"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetTempor" +
            "aryWorkReport\".")]
        public string GetTemporaryWorkReport {
            get {
                return ((string)(this["GetTemporaryWorkReport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetEmploy" +
            "mentAgencyID\".")]
        public string GetEmploymentAgencyID {
            get {
                return ((string)(this["GetEmploymentAgencyID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetEmploy" +
            "mentAgencyCity\".")]
        public string GetEmploymentAgencyCity {
            get {
                return ((string)(this["GetEmploymentAgencyCity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetEmploy" +
            "mentAgencyCountry\".")]
        public string GetEmploymentAgencyCountry {
            get {
                return ((string)(this["GetEmploymentAgencyCountry"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetEmploy" +
            "mentAgencyEmailAdress\".")]
        public string GetEmploymentAgencyEmailAdress {
            get {
                return ((string)(this["GetEmploymentAgencyEmailAdress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetEmploy" +
            "mentAgencyNumber\".")]
        public string GetEmploymentAgencyNumber {
            get {
                return ((string)(this["GetEmploymentAgencyNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetEmploy" +
            "mentAgencyPhoneNumber\".")]
        public string GetEmploymentAgencyPhoneNumber {
            get {
                return ((string)(this["GetEmploymentAgencyPhoneNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetEmploy" +
            "mentAgencyStreet\".")]
        public string GetEmploymentAgencyStreet {
            get {
                return ((string)(this["GetEmploymentAgencyStreet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetEmploy" +
            "mentAgencyRegion\".")]
        public string GetEmploymentAgencyRegion {
            get {
                return ((string)(this["GetEmploymentAgencyRegion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetCountT" +
            "emporaryProfession\".")]
        public string GetEmploymentAgencyPostCode {
            get {
                return ((string)(this["GetEmploymentAgencyPostCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetCountT" +
            "emporaryProfession\".")]
        public string GetCountTemporaryProfession {
            get {
                return ((string)(this["GetCountTemporaryProfession"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetCountT" +
            "emporaryEmploymentAgency\".")]
        public string GetCountAcceptedMissionService {
            get {
                return ((string)(this["GetCountAcceptedMissionService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetCountT" +
            "emporaryEmploymentAgency\".")]
        public string GetCountTemporaryEmploymentAgency {
            get {
                return ((string)(this["GetCountTemporaryEmploymentAgency"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetCountA" +
            "cceptedMissionEmploymentAgency\".")]
        public string GetCountAcceptedMissionEmploymentAgency {
            get {
                return ((string)(this["GetCountAcceptedMissionEmploymentAgency"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetCountR" +
            "ejectedMissionEmploymentAgency\".")]
        public string GetCountRejectedMissionEmploymentAgency {
            get {
                return ((string)(this["GetCountRejectedMissionEmploymentAgency"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetCountW" +
            "aitedMissionEmploymentAgency\".")]
        public string GetCountWaitedMissionEmploymentAgency {
            get {
                return ((string)(this["GetCountWaitedMissionEmploymentAgency"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"InterimDatabase.GetTempor" +
            "aryBirthDate\".")]
        public string GetTemporaryBirthDate {
            get {
                return ((string)(this["GetTemporaryBirthDate"]));
            }
        }
    }
}
