//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterimSearch.Interim_Database.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Interim_Query : global::System.Configuration.ApplicationSettingsBase {
        
        private static Interim_Query defaultInstance = ((Interim_Query)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Interim_Query())));
        
        public static Interim_Query Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT [tbl_temporary].[idTemporary] FROM [tbl_avaibility]")]
        public string SelectIDTemporary {
            get {
                return ((string)(this["SelectIDTemporary"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@" INNER JOIN [tbl_workTimetable] ON [tbl_avaibility].[idWorkTimetable]=[tbl_workTimetable].[idWorkTimetable] INNER JOIN [tbl_temporary] ON [tbl_avaibility].[idTemporary]=[tbl_temporary].[idTemporary] INNER JOIN [tbl_profession] ON [tbl_temporary].[idProfession]=[tbl_profession].[idProfession] ")]
        public string InnerJoinBasics {
            get {
                return ((string)(this["InnerJoinBasics"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" INNER JOIN [tbl_city] ON [tbl_temporary].[idCity]=[tbl_city].[idCity]")]
        public string InnerJoinCity {
            get {
                return ((string)(this["InnerJoinCity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@" WHERE [tbl_avaibility].[idService] IS NULL AND ([tbl_avaibility].[avaibility_AcceptedMission]=0 OR [tbl_avaibility].[avaibility_AcceptedMission] IS NULL) AND [tbl_avaibility].[avaibility_Date]=@Date AND [tbl_workTimetable].[workTimetable_Start]=@WorkTimetableStart AND [tbl_workTimetable].[workTimetable_End]=@WorkTimetableEnd AND [tbl_temporary].[temporary_Certified]=@IsCertified")]
        public string ClauseBasics {
            get {
                return ((string)(this["ClauseBasics"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" AND [tbl_profession].[profession_Name]=@Profession")]
        public string ClauseProfession {
            get {
                return ((string)(this["ClauseProfession"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" AND [tbl_temporary].[temporary_BirthDate] BETWEEN @AgeYearOld AND @AgeYearRecent" +
            "")]
        public string ClauseBirthDate {
            get {
                return ((string)(this["ClauseBirthDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" AND [tbl_temporary].[temporary_StartDateExperience] BETWEEN @NbrYearExpOld AND @" +
            "NbrYearExpRecent")]
        public string ClauseSartDateExp {
            get {
                return ((string)(this["ClauseSartDateExp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Date")]
        public string Date {
            get {
                return ((string)(this["Date"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WorkTimetableStart")]
        public string WorkTimetableStart {
            get {
                return ((string)(this["WorkTimetableStart"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IsCertified")]
        public string IsCertified {
            get {
                return ((string)(this["IsCertified"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Profession")]
        public string Profession {
            get {
                return ((string)(this["Profession"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AgeYearOld")]
        public string AgeYearOld {
            get {
                return ((string)(this["AgeYearOld"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AgeYearRecent")]
        public string AgeYearRecent {
            get {
                return ((string)(this["AgeYearRecent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NbrYearExpOld")]
        public string NbrYearExpOld {
            get {
                return ((string)(this["NbrYearExpOld"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NbrYearExpRecent")]
        public string NbrYearExpRecent {
            get {
                return ((string)(this["NbrYearExpRecent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" ORDER BY [tbl_temporary].[temporary_Name];")]
        public string OrderBy {
            get {
                return ((string)(this["OrderBy"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WorkTimetableEnd")]
        public string WorkTimetableEnd {
            get {
                return ((string)(this["WorkTimetableEnd"]));
            }
        }
    }
}
