//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterimSearch.Interim_Database.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Interim_Proc : global::System.Configuration.ApplicationSettingsBase {
        
        private static Interim_Proc defaultInstance = ((Interim_Proc)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Interim_Proc())));
        
        public static Interim_Proc Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetWorkTimetable")]
        public string Proc_GetWorkTimetable {
            get {
                return ((string)(this["Proc_GetWorkTimetable"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetProfession")]
        public string Proc_GetProfession {
            get {
                return ((string)(this["Proc_GetProfession"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetTemporaryName")]
        public string Proc_GetTemporaryName {
            get {
                return ((string)(this["Proc_GetTemporaryName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetTemporaryFirstName")]
        public string Proc_GetTemporaryFirstName {
            get {
                return ((string)(this["Proc_GetTemporaryFirstName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetTemporaryNbrYearExp")]
        public string Proc_GetTemporaryNbrYearExp {
            get {
                return ((string)(this["Proc_GetTemporaryNbrYearExp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetTemporaryCity")]
        public string Proc_GetTemporaryCity {
            get {
                return ((string)(this["Proc_GetTemporaryCity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetTemporaryAge")]
        public string Proc_GetTemporaryAge {
            get {
                return ((string)(this["Proc_GetTemporaryAge"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetTemporaryTitle")]
        public string Proc_GetTemporaryTitle {
            get {
                return ((string)(this["Proc_GetTemporaryTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetService")]
        public string Proc_GetService {
            get {
                return ((string)(this["Proc_GetService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetTemporaryEmailAdress")]
        public string Proc_GetTemporaryEmailAdress {
            get {
                return ((string)(this["Proc_GetTemporaryEmailAdress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_SetSendDateAndService")]
        public string Proc_SetSendDateAndService {
            get {
                return ((string)(this["Proc_SetSendDateAndService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetAvaibilityID")]
        public string Proc_GetAvaibilityID {
            get {
                return ((string)(this["Proc_GetAvaibilityID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetTemporaryStreet")]
        public string Proc_GetTemporaryStreet {
            get {
                return ((string)(this["Proc_GetTemporaryStreet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetTemporaryNumber")]
        public string Proc_GetTemporaryNumber {
            get {
                return ((string)(this["Proc_GetTemporaryNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetTemporaryPostCode")]
        public string Proc_GetTemporaryPostCode {
            get {
                return ((string)(this["Proc_GetTemporaryPostCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetTemporaryRegion")]
        public string Proc_GetTemporaryRegion {
            get {
                return ((string)(this["Proc_GetTemporaryRegion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetTemporaryPhoneNumber")]
        public string Proc_GetTemporaryPhoneNumber {
            get {
                return ((string)(this["Proc_GetTemporaryPhoneNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetTemporaryProfession")]
        public string Proc_GetTemporaryProfession {
            get {
                return ((string)(this["Proc_GetTemporaryProfession"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetTemporaryEmploymentAgency")]
        public string Proc_GetTemporaryEmploymentAgency {
            get {
                return ((string)(this["Proc_GetTemporaryEmploymentAgency"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetTemporaryCertified")]
        public string Proc_GetTemporaryCertified {
            get {
                return ((string)(this["Proc_GetTemporaryCertified"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetAvaibilityDate")]
        public string Proc_GetAvaibilityDate {
            get {
                return ((string)(this["Proc_GetAvaibilityDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetAvaibilityIDAll")]
        public string Proc_GetAvaibilityIDAll {
            get {
                return ((string)(this["Proc_GetAvaibilityIDAll"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetAvaibilityTemporaryID")]
        public string Proc_GetAvaibilityTemporaryID {
            get {
                return ((string)(this["Proc_GetAvaibilityTemporaryID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetTemporaryService")]
        public string Proc_GetTemporaryService {
            get {
                return ((string)(this["Proc_GetTemporaryService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetTemporarySendDate")]
        public string Proc_GetTemporarySendDate {
            get {
                return ((string)(this["Proc_GetTemporarySendDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetTemporaryAcceptedMission")]
        public string Proc_GetTemporaryAcceptedMission {
            get {
                return ((string)(this["Proc_GetTemporaryAcceptedMission"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_SetStateMission")]
        public string Proc_SetStateMission {
            get {
                return ((string)(this["Proc_SetStateMission"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetTemporaryDate")]
        public string Proc_GetTemporaryDate {
            get {
                return ((string)(this["Proc_GetTemporaryDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetTemporaryWorkTimetableStart")]
        public string Proc_GetTemporaryWorkTimetableStart {
            get {
                return ((string)(this["Proc_GetTemporaryWorkTimetableStart"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetTemporaryWorkTimetableEnd")]
        public string Proc_GetTemporaryWorkTimetableEnd {
            get {
                return ((string)(this["Proc_GetTemporaryWorkTimetableEnd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_SetAbortMission")]
        public string Proc_SetAbortMission {
            get {
                return ((string)(this["Proc_SetAbortMission"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetAbortAvaibilityID")]
        public string Proc_GetAbortAvaibilityID {
            get {
                return ((string)(this["Proc_GetAbortAvaibilityID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetAvaibilityWorkTimetable")]
        public string Proc_GetAvaibilityWorkTimetable {
            get {
                return ((string)(this["Proc_GetAvaibilityWorkTimetable"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetTemporaryWorkReport")]
        public string Proc_GetTemporaryWorkReport {
            get {
                return ((string)(this["Proc_GetTemporaryWorkReport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetEmploymentAgencyID")]
        public string Proc_GetEmploymentAgencyID {
            get {
                return ((string)(this["Proc_GetEmploymentAgencyID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetEmploymentAgencyCity")]
        public string Proc_GetEmploymentAgencyCity {
            get {
                return ((string)(this["Proc_GetEmploymentAgencyCity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetEmploymentAgencyCountry")]
        public string Proc_GetEmploymentAgencyCountry {
            get {
                return ((string)(this["Proc_GetEmploymentAgencyCountry"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetEmploymentAgencyEmailAdress")]
        public string Proc_GetEmploymentAgencyEmailAdress {
            get {
                return ((string)(this["Proc_GetEmploymentAgencyEmailAdress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetEmploymentAgencyNumber")]
        public string Proc_GetEmploymentAgencyNumber {
            get {
                return ((string)(this["Proc_GetEmploymentAgencyNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetEmploymentAgencyPhoneNumber")]
        public string Proc_GetEmploymentAgencyPhoneNumber {
            get {
                return ((string)(this["Proc_GetEmploymentAgencyPhoneNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetEmploymentAgencyPostCode")]
        public string Proc_GetEmploymentAgencyPostCode {
            get {
                return ((string)(this["Proc_GetEmploymentAgencyPostCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetEmploymentAgencyRegion")]
        public string Proc_GetEmploymentAgencyRegion {
            get {
                return ((string)(this["Proc_GetEmploymentAgencyRegion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetEmploymentAgencyStreet")]
        public string Proc_GetEmploymentAgencyStreet {
            get {
                return ((string)(this["Proc_GetEmploymentAgencyStreet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetCountTemporaryProfession")]
        public string Proc_GetCountTemporaryProfession {
            get {
                return ((string)(this["Proc_GetCountTemporaryProfession"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetCountAcceptedMissionService")]
        public string Proc_GetCountAcceptedMissionService {
            get {
                return ((string)(this["Proc_GetCountAcceptedMissionService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetCountTemporaryEmploymentAgency")]
        public string Proc_GetCountTemporaryEmploymentAgency {
            get {
                return ((string)(this["Proc_GetCountTemporaryEmploymentAgency"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetCountWaitedMissionEmploymentAgency")]
        public string Proc_GetCountWaitedMissionEmploymentAgency {
            get {
                return ((string)(this["Proc_GetCountWaitedMissionEmploymentAgency"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetCountRejectedMissionEmploymentAgency")]
        public string Proc_GetCountRejectedMissionEmploymentAgency {
            get {
                return ((string)(this["Proc_GetCountRejectedMissionEmploymentAgency"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetCountAcceptedMissionEmploymentAgency")]
        public string Proc_GetCountAcceptedMissionEmploymentAgency {
            get {
                return ((string)(this["Proc_GetCountAcceptedMissionEmploymentAgency"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proc_GetTemporaryBirthDate")]
        public string Proc_GetTemporaryBirthDate {
            get {
                return ((string)(this["Proc_GetTemporaryBirthDate"]));
            }
        }
    }
}
