//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterimSearch.Interim_Database.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Interim_Code : global::System.Configuration.ApplicationSettingsBase {
        
        private static Interim_Code defaultInstance = ((Interim_Code)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Interim_Code())));
        
        public static Interim_Code Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=\"|DataDirectory|\\Interim Database\\Da" +
            "tabase\\Interim.mdf\";Integrated Security=True")]
        public string InterimDatabaseConnectionString {
            get {
                return ((string)(this["InterimDatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0:yyyy-MM-dd}")]
        public string DateTimeFormatDatabase {
            get {
                return ((string)(this["DateTimeFormatDatabase"]));
            }
        }
    }
}
