//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterimSearch.Interim_Database.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Interim_Fields : global::System.Configuration.ApplicationSettingsBase {
        
        private static Interim_Fields defaultInstance = ((Interim_Fields)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Interim_Fields())));
        
        public static Interim_Fields Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("idTemporary")]
        public string IDTemporary {
            get {
                return ((string)(this["IDTemporary"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("temporary_Title")]
        public string Temporary_Title {
            get {
                return ((string)(this["Temporary_Title"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("temporary_Name")]
        public string Temporary_Name {
            get {
                return ((string)(this["Temporary_Name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("temporary_FirstName")]
        public string Temporary_FirstName {
            get {
                return ((string)(this["Temporary_FirstName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("temporary_YearBirthDate")]
        public string Temporary_YearBirthDate {
            get {
                return ((string)(this["Temporary_YearBirthDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("temporary_Street")]
        public string Temporary_Street {
            get {
                return ((string)(this["Temporary_Street"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("temporary_Number")]
        public string Temporary_Number {
            get {
                return ((string)(this["Temporary_Number"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("temporary_PostCode")]
        public string Temporary_PostCode {
            get {
                return ((string)(this["Temporary_PostCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("city_Name")]
        public string City_Name {
            get {
                return ((string)(this["City_Name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("region_Name")]
        public string Region_Name {
            get {
                return ((string)(this["Region_Name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("temporary_PhoneNumber")]
        public string Temporary_PhoneNumber {
            get {
                return ((string)(this["Temporary_PhoneNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("temporary_EmailAdress")]
        public string Temporary_EmailAdress {
            get {
                return ((string)(this["Temporary_EmailAdress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("temporary_Certified")]
        public string Temporary_Certified {
            get {
                return ((string)(this["Temporary_Certified"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("temporary_YearStartDateExperience")]
        public string Temporary_YearStartDateExperience {
            get {
                return ((string)(this["Temporary_YearStartDateExperience"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("profession_Name")]
        public string Profession_Name {
            get {
                return ((string)(this["Profession_Name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("employmentAgency_Name")]
        public string EmploymentAgency_Name {
            get {
                return ((string)(this["EmploymentAgency_Name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("idAvaibility")]
        public string IDAvaibility {
            get {
                return ((string)(this["IDAvaibility"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("avaibility_Date")]
        public string Avaibility_Date {
            get {
                return ((string)(this["Avaibility_Date"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("idWorkTimetable")]
        public string IDWorkTimetable {
            get {
                return ((string)(this["IDWorkTimetable"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("avaibility_SendDate")]
        public string Avaibility_SendDate {
            get {
                return ((string)(this["Avaibility_SendDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("avaibility_AcceptedMission")]
        public string Avaibility_AcceptedMission {
            get {
                return ((string)(this["Avaibility_AcceptedMission"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DateNow")]
        public string DateNow {
            get {
                return ((string)(this["DateNow"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("workTimetable_Start")]
        public string WorkTimetable_Start {
            get {
                return ((string)(this["WorkTimetable_Start"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("workTimetable_End")]
        public string WorkTimetable_End {
            get {
                return ((string)(this["WorkTimetable_End"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("service_Name")]
        public string Service_Name {
            get {
                return ((string)(this["Service_Name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("idEmploymentAgency")]
        public string IDEmploymentAgency {
            get {
                return ((string)(this["IDEmploymentAgency"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("country_Name")]
        public string Country_Name {
            get {
                return ((string)(this["Country_Name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("employmentAgency_EmailAdress")]
        public string EmploymentAgency_EmailAdress {
            get {
                return ((string)(this["EmploymentAgency_EmailAdress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("employmentAgency_PhoneNumber")]
        public string EmploymentAgency_PhoneNumber {
            get {
                return ((string)(this["EmploymentAgency_PhoneNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("employmentAgency_Number")]
        public string EmploymentAgency_Number {
            get {
                return ((string)(this["EmploymentAgency_Number"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("employmentAgency_Street")]
        public string EmploymentAgency_Street {
            get {
                return ((string)(this["EmploymentAgency_Street"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("employmentAgency_PostCode")]
        public string EmploymentAgency_PostCode {
            get {
                return ((string)(this["EmploymentAgency_PostCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("count_Temporary")]
        public string Count_Temporary {
            get {
                return ((string)(this["Count_Temporary"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("count_AcceptedMission")]
        public string Count_AcceptedMission {
            get {
                return ((string)(this["Count_AcceptedMission"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("count_RejectedMission")]
        public string Count_RejectedMission {
            get {
                return ((string)(this["Count_RejectedMission"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("count_WaitedMission")]
        public string Count_WaitedMission {
            get {
                return ((string)(this["Count_WaitedMission"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("temporary_BirthDate")]
        public string Temporary_BirthDate {
            get {
                return ((string)(this["Temporary_BirthDate"]));
            }
        }
    }
}
